<script setup>
import AppIcon from './ui/AppIcon.vue';
import { company } from '../data/site';

/*
 * Stylised UAE map drawn as plain SVG (no map library). The geometry is computed once here —
 * at build time for the pre-rendered HTML, and identically in the browser — so there is no runtime cost.
 * Outline is a simplified coastline/border; the dot matrix is generated by point-in-polygon.
 */
const outline = [
  [51.58, 24.25], [51.76, 24.29], [51.79, 24.02], [52.1, 23.97], [52.58, 24.18], [53.0, 24.12],
  [53.4, 24.15], [54.0, 24.12], [54.37, 24.45], [54.69, 24.8], [55.05, 25.02], [55.27, 25.26],
  [55.44, 25.44], [55.6, 25.58], [55.85, 25.75], [56.07, 26.06], [56.26, 25.71], [56.37, 25.35],
  [56.36, 25.12], [56.38, 24.92], [55.89, 24.92], [55.8, 24.27], [55.98, 24.13], [55.53, 23.93],
  [55.53, 23.52], [55.23, 23.11], [55.21, 22.71], [55.01, 22.5], [52.0, 23.0], [51.62, 24.01],
];

const LON0 = 51.3;
const LAT0 = 26.35;
const K = 150; // px per degree of latitude
const KX = K * Math.cos((24.3 * Math.PI) / 180);
const W = Math.round((56.65 - LON0) * KX);
const H = Math.round((LAT0 - 22.25) * K);

const project = ([lon, lat]) => [(lon - LON0) * KX, (LAT0 - lat) * K];
const pts = outline.map(project);
const outlinePath = 'M' + pts.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join('L') + 'Z';

function inside(x, y) {
  let hit = false;
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    const [xi, yi] = pts[i];
    const [xj, yj] = pts[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) hit = !hit;
  }
  return hit;
}

const STEP = 11;
let dots = '';
for (let y = STEP / 2; y < H; y += STEP) {
  for (let x = STEP / 2; x < W; x += STEP) {
    if (inside(x, y)) dots += `M${x.toFixed(1)} ${y.toFixed(1)}h0`;
  }
}

// Geographic reference points only — not a statement of service coverage.
// `minor` labels are hidden on small screens where they would collide.
const base = { name: 'Beda Zayed', sub: 'Al Dhafra · Base', xy: project([53.7, 23.68]) };
const places = [
  { name: 'Abu Dhabi', ll: [54.37, 24.45], anchor: 'end', dx: -10, dy: -8, minor: false },
  { name: 'Dubai', ll: [55.27, 25.2], anchor: 'end', dx: -10, dy: -6, minor: false },
  { name: 'Sharjah', ll: [55.42, 25.35], anchor: 'end', dx: -10, dy: -6, minor: true },
  { name: 'Ras Al Khaimah', ll: [55.94, 25.79], anchor: 'end', dx: -10, dy: -6, minor: false },
  { name: 'Fujairah', ll: [56.33, 25.12], anchor: 'end', dx: -12, dy: 22, minor: false },
  { name: 'Al Ain', ll: [55.76, 24.21], anchor: 'start', dx: 10, dy: 4, minor: false },
  { name: 'Ruwais', ll: [52.73, 24.11], anchor: 'middle', dx: 0, dy: -12, minor: true },
].map((p) => ({ ...p, xy: project(p.ll) }));

const [bx, by] = base.xy;

// Curved illustrative connectors from the base to each reference point
const arcs = places.map((p, i) => {
  const [x, y] = p.xy;
  const bend = 0.22 * (i % 2 === 0 ? 1 : -1);
  const cx = (bx + x) / 2 - (y - by) * bend;
  const cy = (by + y) / 2 + (x - bx) * bend;
  return `M${bx.toFixed(1)} ${by.toFixed(1)}Q${cx.toFixed(1)} ${cy.toFixed(1)} ${x.toFixed(1)} ${y.toFixed(1)}`;
});

const translate = ([x, y]) => `translate(${x.toFixed(1)} ${y.toFixed(1)})`;
</script>

<template>
  <section id="uae" class="section uae" aria-labelledby="uae-title">
    <div class="container uae__grid">
      <div class="uae__content">
        <p class="eyebrow" data-reveal>UAE Logistics</p>
        <h2 id="uae-title" data-reveal style="--reveal-delay: 80">
          Moving Cargo <span class="text-gradient">Across the UAE.</span>
        </h2>
        <p class="lead" data-reveal style="--reveal-delay: 160">
          Based in the Al Dhafra region of Abu Dhabi, Wadi Nushakal is a UAE transport company built around local
          knowledge, dependable service and cargo that keeps moving.
        </p>

        <dl class="uae__facts" data-reveal style="--reveal-delay: 220">
          <div class="uae__fact">
            <dt><AppIcon name="pin" :size="18" />Base</dt>
            <dd>Beda Zayed Industrial Area</dd>
          </div>
          <div class="uae__fact">
            <dt><AppIcon name="map" :size="18" />Region</dt>
            <dd>Al Dhafra, Abu Dhabi</dd>
          </div>
          <div class="uae__fact">
            <dt><AppIcon name="route" :size="18" />Country</dt>
            <dd>United Arab Emirates</dd>
          </div>
        </dl>

        <a class="btn btn--ghost" :href="company.address.mapsHref" target="_blank" rel="noopener noreferrer" data-reveal>
          View location on map
          <AppIcon name="arrow-up-right" class="arrow" />
          <span class="visually-hidden">(opens in a new tab)</span>
        </a>
      </div>

      <figure class="uae__map panel" data-reveal="scale" data-map>
        <div class="uae__map-top" aria-hidden="true">
          <span class="uae__map-tag"><span class="uae__dot"></span>Network view</span>
          <span class="uae__coords">23.68° N · 53.70° E</span>
        </div>

        <svg :viewBox="`0 0 ${W} ${H}`" role="img" aria-labelledby="uae-map-title uae-map-desc" class="uae__svg">
          <title id="uae-map-title">Stylised map of the United Arab Emirates</title>
          <desc id="uae-map-desc">
            Illustrative map highlighting Wadi Nushakal's base in Beda Zayed, Al Dhafra, with reference points for
            major UAE cities.
          </desc>
          <defs>
            <radialGradient id="uae-base-glow">
              <stop offset="0" stop-color="#4a83b8" stop-opacity="0.35" />
              <stop offset="1" stop-color="#4a83b8" stop-opacity="0" />
            </radialGradient>
            <linearGradient id="uae-arc" x1="0" x2="1">
              <stop offset="0" stop-color="#7fa9d1" />
              <stop offset="1" stop-color="#2f6497" />
            </linearGradient>
          </defs>

          <path :d="outlinePath" class="uae__land" />
          <path :d="dots" class="uae__dots" />
          <path :d="outlinePath" class="uae__coast" />

          <g class="uae__arcs">
            <path v-for="(d, i) in arcs" :key="`a${i}`" :d="d" pathLength="1" :style="{ '--i': i }" />
          </g>
          <g class="uae__pulses">
            <path v-for="(d, i) in arcs" :key="`p${i}`" :d="d" pathLength="100" :style="{ '--i': i }" />
          </g>

          <g class="uae__places">
            <g
              v-for="(p, i) in places"
              :key="p.name"
              :transform="translate(p.xy)"
              :class="{ 'uae__place--minor': p.minor }"
              :style="{ '--i': i }"
            >
              <circle r="9" class="uae__place-ring" />
              <circle r="3.6" class="uae__place-dot" />
              <text :x="p.dx" :y="p.dy" :text-anchor="p.anchor">{{ p.name }}</text>
            </g>
          </g>

          <g class="uae__base" :transform="translate(base.xy)">
            <circle r="60" fill="url(#uae-base-glow)" />
            <circle r="16" class="uae__base-ring" />
            <circle r="16" class="uae__base-ring uae__base-ring--2" />
            <circle r="7" class="uae__base-dot" />
            <text x="0" y="36" text-anchor="middle" class="uae__base-name">{{ base.name }}</text>
            <text x="0" y="54" text-anchor="middle" class="uae__base-sub">{{ base.sub }}</text>
          </g>
        </svg>

        <figcaption class="uae__caption">Stylised visualisation for illustration only.</figcaption>
      </figure>
    </div>
  </section>
</template>

<style scoped>
.uae {
  overflow: hidden;
}

.uae__grid {
  display: grid;
  gap: clamp(3rem, 6vw, 5rem);
  align-items: center;
}

@media (min-width: 1100px) {
  .uae__grid {
    grid-template-columns: minmax(0, 1fr) minmax(0, 1.1fr);
  }
}

.uae__content {
  display: grid;
  gap: 1.4rem;
  justify-items: start;
}

.uae__facts {
  display: grid;
  width: 100%;
  margin: 0.5rem 0 0.75rem;
  border-top: 1px solid var(--line-2);
}

.uae__fact {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  padding-block: 0.95rem;
  border-bottom: 1px solid var(--line-2);
}

.uae__fact dt {
  display: inline-flex;
  align-items: center;
  gap: 0.6rem;
  color: var(--muted);
  font-size: 0.85rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.uae__fact dt svg {
  color: var(--brand-strong);
}

.uae__fact dd {
  font-weight: 650;
  text-align: right;
  color: var(--text);
}

/* Map card */
.uae__map {
  position: relative;
  margin: 0;
  padding: clamp(1rem, 2.5vw, 1.75rem);
  border-radius: var(--radius-lg);
  background:
    radial-gradient(80% 60% at 40% 60%, rgba(74, 131, 184, 0.06), transparent 70%),
    var(--surface);
  overflow: hidden;
}

.uae__map::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image:
    linear-gradient(rgba(15, 27, 42, 0.04) 1px, transparent 1px),
    linear-gradient(90deg, rgba(15, 27, 42, 0.04) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events: none;
}

.uae__map-top {
  position: relative;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  font-size: 0.72rem;
  font-weight: 600;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--muted);
}

.uae__map-tag {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.35rem 0.7rem;
  border-radius: 999px;
  border: 1px solid var(--line-2);
  color: var(--text-2);
  background: var(--surface);
}

.uae__dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--brand);
}

.uae__coords {
  font-variant-numeric: tabular-nums;
}

.uae__svg {
  position: relative;
  width: 100%;
  height: auto;
  margin-top: 0.5rem;
  overflow: visible;
}

.uae__land {
  fill: rgba(74, 131, 184, 0.06);
}

.uae__dots {
  stroke: rgba(15, 27, 42, 0.2);
  stroke-width: 2.6;
  stroke-linecap: round;
}

.uae__coast {
  fill: none;
  stroke: var(--brand);
  stroke-opacity: 0.75;
  stroke-width: 1.4;
  stroke-linejoin: round;
}

.uae__arcs path {
  fill: none;
  stroke: url(#uae-arc);
  stroke-width: 1.8;
  stroke-linecap: round;
  stroke-dasharray: 1;
  stroke-dashoffset: 1;
}

/* Travelling highlights along the arcs (no SVG filters — those force expensive repaints) */
.uae__pulses path {
  fill: none;
  stroke: var(--brand-strong);
  stroke-width: 3.5;
  stroke-linecap: round;
  stroke-dasharray: 6 94;
  stroke-dashoffset: 0;
  opacity: 0;
}

.uae__places text,
.uae__base text {
  fill: var(--text-2);
  font-size: 13px;
  font-weight: 600;
  font-family: var(--font);
  paint-order: stroke;
  stroke: rgba(255, 255, 255, 0.92);
  stroke-width: 4px;
}

.uae__place-dot {
  fill: var(--brand-deep);
}

.uae__place-ring {
  fill: #fff;
  stroke: rgba(15, 27, 42, 0.2);
}

.uae__places g {
  opacity: 0;
  transition: opacity 0.5s ease;
  transition-delay: calc(0.8s + var(--i) * 0.1s);
}

.uae__base-dot {
  fill: var(--brand-strong);
  stroke: #fff;
  stroke-width: 2.5;
}

.uae__base-ring {
  fill: none;
  stroke: var(--brand);
  stroke-width: 1.5;
  transform-box: fill-box;
  transform-origin: center;
}

.uae__base .uae__base-name {
  fill: var(--text);
  font-size: 15px;
  font-weight: 700;
}

.uae__base .uae__base-sub {
  fill: var(--brand-deep);
  font-size: 11px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

/* Animated state (added by lib/reveal.js when the map scrolls into view) */
.uae__map.is-live .uae__arcs path {
  stroke-dashoffset: 0;
  transition: stroke-dashoffset 1.4s var(--ease-out);
  transition-delay: calc(0.3s + var(--i) * 0.1s);
}

.uae__map.is-live .uae__pulses path {
  opacity: 1;
  animation: arc-pulse 3.6s linear infinite;
  animation-delay: calc(1.8s + var(--i) * 0.5s);
}

.uae__map.is-live .uae__places g {
  opacity: 1;
}

.uae__map.is-live .uae__base-ring {
  animation: base-ping 3s var(--ease-out) infinite;
}

.uae__map.is-live .uae__base-ring--2 {
  animation-delay: 1.5s;
}

@keyframes arc-pulse {
  from {
    stroke-dashoffset: 100;
  }
  to {
    stroke-dashoffset: 0;
  }
}

@keyframes base-ping {
  0% {
    transform: scale(0.6);
    opacity: 0.9;
  }
  100% {
    transform: scale(2.6);
    opacity: 0;
  }
}

.uae__caption {
  position: relative;
  margin-top: 0.75rem;
  font-size: 0.78rem;
  color: var(--muted);
}

/* The SVG scales down on phones, so labels are drawn larger in map units to stay ~11–12px on screen */
@media (max-width: 599px) {
  .uae__places text {
    font-size: 25px;
    stroke-width: 6px;
  }
  .uae__place--minor text {
    display: none;
  }
  .uae__base .uae__base-name {
    font-size: 27px;
  }
  .uae__base .uae__base-sub {
    font-size: 19px;
  }
  .uae__coords {
    display: none;
  }
}

@media (prefers-reduced-motion: reduce) {
  .uae__map .uae__arcs path {
    stroke-dashoffset: 0;
  }
  .uae__map .uae__places g {
    opacity: 1;
  }
  .uae__map.is-live .uae__pulses path {
    opacity: 0;
  }
}
</style>
